### ISSUE TITLE
only load variables specificed in configuration object

### ISSUE THREAD

**Issue by brettatoms** [brettlangdon/flask-env#1]
I think it would be more helpful and potentially less dangerous to only load variables that are defined in your configuration object.  Currently every defined environment variable is set in the flask config which is unnecessary and potentially dangerous if there's an environment variable defined that flask or some extension is using that you don't know about.

**Comment by brettlangdon** [comment]
Hey @brettatoms, thanks for the suggestion. Unfortunately I am on vacation for the next month, but I'll be sure to give this some thought and we'll see what we can do.

**Comment by brettlangdon** [comment]
@brettatoms sorry for the long delay here. I have opened up PR #2 to address this concern.

By default `Flask-Env` will not load all environment variables, just those predefined on the configuration object. However, there is a new setting `ENV_LOAD_ALL`, which when set to `True` will use the previous behavior of loading everything from `os.environ` onto the configuration object.
