### ISSUE TITLE
A description of my usage of this.

### ISSUE THREAD

**Issue by nackjicholson** [brettlangdon/flask-env#4]
Just so you're aware of one particular use out there that is happening with your code.

I use this for flask servers yes, but I've learned there's nothing flask specific about this despite it's name. I can pull environmental configs for a CLI as well, or any program really.

I am using this in several CLI only projects to pull prefixed environment variables.

Cheers! Thanks for sharing this package; it has been really useful!

**Comment by brettlangdon** [comment]
@nackjicholson thank you for sharing!

I sort of realized after building this package that it isn't necessarily Flask specific, but I haven't taken the time to re-release as a generic package. If only the days were longer :)
